/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author honha
 */
public class frmReadWriteFile extends javax.swing.JFrame {

    private int role;
    /**
     * Creates new form frmReadWriteFile
     */
    public frmReadWriteFile() {
        initComponents();
        
        this.setLocationRelativeTo(null);
         

    }
    
    frmReadWriteFile(int role){
        this.role=role;
        setPermissions();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtChuoi = new javax.swing.JTextField();
        txtTenTap = new javax.swing.JTextField();
        txtNoiDung = new javax.swing.JTextField();
        btnDocNP = new javax.swing.JButton();
        btnDocVB = new javax.swing.JButton();
        btnGhiNP = new javax.swing.JButton();
        btnGhiVB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập tên tập tin");

        jLabel2.setText("Nhập chuỗi");

        jLabel3.setText("Nội dung file");

        btnDocNP.setText("Đọc File nhị phân");
        btnDocNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocNPActionPerformed(evt);
            }
        });

        btnDocVB.setText("Đọc File văn bản");
        btnDocVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocVBActionPerformed(evt);
            }
        });

        btnGhiNP.setText("Ghi File nhị phân");
        btnGhiNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiNPActionPerformed(evt);
            }
        });

        btnGhiVB.setText("Ghi File văn bản");
        btnGhiVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiVBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTap, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDocNP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDocVB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGhiNP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGhiVB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtTenTap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocNP)
                    .addComponent(btnGhiNP))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGhiVB)
                    .addComponent(btnDocVB))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGhiNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiNPActionPerformed
         byte a[]= new byte [20];
        File file;
        int i;
        char s[]=txtChuoi.getText().toCharArray();
        for(i=0;i<s.length;i++){
            a[i]=(byte)s[i];
        }
        try{
            file = new File(txtTenTap.getText());
            FileOutputStream fi = new FileOutputStream(file);
            fi.write(a);
            fi.close();
            
        }catch(IOException e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGhiNPActionPerformed

    private void btnDocNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocNPActionPerformed
         byte a[];
        File file;
        try{
            file = new File(txtTenTap.getText());
            FileInputStream fo = new FileInputStream(file);
            a= new byte[fo.available()];
            fo.read(a);
            fo.close();
            txtNoiDung.setText(new String(a));
        }catch(IOException e){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocNPActionPerformed

    private void btnGhiVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiVBActionPerformed
        try{
            FileWriter fw = new FileWriter(new File(txtTenTap.getText()));
            fw.write(txtChuoi.getText());
            fw.close();
        }catch(Exception e){
            e.printStackTrace();
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnGhiVBActionPerformed

    private void btnDocVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocVBActionPerformed
        try{
            FileReader fr = new FileReader(new File(txtTenTap.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[]= new char[5];
            while(fr.ready()){
                int len = fr.read(ca);
                sb.append(ca,0,len);
            }
            fr.close();
            txtNoiDung.setText(sb+"");
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocVBActionPerformed
              private void setPermissions() {
        if (role == 1) {
            btnDocNP.setEnabled(true);   // Enable read buttons
            btnDocVB.setEnabled(true);
            btnGhiNP.setEnabled(false);  // Disable write buttons
            btnGhiVB.setEnabled(false);
        } else if (role==2) {
            btnDocNP.setEnabled(false);   // Enable both read and write buttons
            btnDocVB.setEnabled(false);
            btnGhiNP.setEnabled(true);
            btnGhiVB.setEnabled(true);
        } else {
           btnDocNP.setEnabled(false);   // Enable both read and write buttons
            btnDocVB.setEnabled(false);
            btnGhiNP.setEnabled(false);
            btnGhiVB.setEnabled(false);  
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReadWriteFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocNP;
    private javax.swing.JButton btnDocVB;
    private javax.swing.JButton btnGhiNP;
    private javax.swing.JButton btnGhiVB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtChuoi;
    private javax.swing.JTextField txtNoiDung;
    private javax.swing.JTextField txtTenTap;
    // End of variables declaration//GEN-END:variables
}
