/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Administrator
 */
public class ReadWriteFile extends javax.swing.JFrame {

    /**
     * Creates new form ReadWriteFile
     */
    public ReadWriteFile() {
        
        initComponents();
        this.setLocationRelativeTo(null);

    }

    
    //fetchPermissiomn
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGhiVB = new javax.swing.JButton();
        btnDocNP = new javax.swing.JButton();
        btnDocVB = new javax.swing.JButton();
        btnGhiNP = new javax.swing.JButton();
        txtTenTap = new javax.swing.JTextField();
        txtNoiDung = new javax.swing.JTextField();
        txtChuoi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập tên tập tin");

        jLabel2.setText("Nhập chuỗi");

        jLabel3.setText("Nội dung file");

        btnGhiVB.setText("Ghi File văn bản");
        btnGhiVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiVBActionPerformed(evt);
            }
        });

        btnDocNP.setText("Đọc File nhị phân ");
        btnDocNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocNPActionPerformed(evt);
            }
        });

        btnDocVB.setText("Đọc File văn bản");
        btnDocVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocVBActionPerformed(evt);
            }
        });

        btnGhiNP.setText("Ghi File nhị phân");
        btnGhiNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiNPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenTap, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDocVB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGhiVB))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDocNP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGhiNP)))))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenTap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGhiNP)
                    .addComponent(btnDocNP))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocVB)
                    .addComponent(btnGhiVB))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGhiNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiNPActionPerformed
        byte a[]= new byte [20];
        File file;
        int i;
        char s[]=txtChuoi.getText().toCharArray();
        for(i=0;i<s.length;i++){
            a[i]=(byte)s[i];
        }
        try{
            file = new File(txtTenTap.getText());
            FileOutputStream fi = new FileOutputStream(file);
            fi.write(a);
            fi.close();
            
        }catch(IOException e){
            e.printStackTrace();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGhiNPActionPerformed

    private void btnDocNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocNPActionPerformed
        byte a[];
        File file;
        try{
            file = new File(txtTenTap.getText());
            FileInputStream fo = new FileInputStream(file);
            a= new byte[fo.available()];
            fo.read(a);
            fo.close();
            txtNoiDung.setText(new String(a));
        }catch(IOException e){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocNPActionPerformed

    private void btnGhiVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiVBActionPerformed
        try{
            FileWriter fw = new FileWriter(new File(txtTenTap.getText()));
            fw.write(txtChuoi.getText());
            fw.close();
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGhiVBActionPerformed

    private void btnDocVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocVBActionPerformed
        try{
            FileReader fr = new FileReader(new File(txtTenTap.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[]= new char[5];
            while(fr.ready()){
                int len = fr.read(ca);
                sb.append(ca,0,len);
            }
            fr.close();
            txtNoiDung.setText(sb+"");
        }catch(Exception e){
            e.printStackTrace();
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnDocVBActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadWriteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadWriteFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocNP;
    private javax.swing.JButton btnDocVB;
    private javax.swing.JButton btnGhiNP;
    private javax.swing.JButton btnGhiVB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtChuoi;
    private javax.swing.JTextField txtNoiDung;
    private javax.swing.JTextField txtTenTap;
    // End of variables declaration//GEN-END:variables
}
