/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai3;

import java.net.Inet4Address;
import java.net.InetAddress;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class frmthltm extends javax.swing.JFrame {

    /**
     * Creates new form frmthltm
     */
    public frmthltm() {
        initComponents();
                this.setLocationRelativeTo(null);
                this.setTitle("Thực hành lập trình mạng");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbHeThong = new javax.swing.JComboBox();
        cmbChucNang = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbHeThong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hệ thống", " ", " " }));
        cmbHeThong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHeThongActionPerformed(evt);
            }
        });

        cmbChucNang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chức năng", "Kiểm tra IP", "Tìm IP của tên miền", "Tìm tên miền của IP", "Tìm IP của máy cục bộ", "Kiểm tra IP.", "Kiểm tra 2 tên miền", " " }));
        cmbChucNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChucNangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cmbHeThong, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 633, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHeThong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(470, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbHeThongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHeThongActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHeThongActionPerformed

    private void cmbChucNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChucNangActionPerformed
              String selectedItem =  cmbChucNang.getSelectedItem().toString();
        if (selectedItem.equals("Kiểm tra IP")) {
            // Mở cửa sổ mới khi chọn mục 1
           frmKTip readFiled = new frmKTip();
           
           readFiled.setVisible(true);
           

        
        } else if (selectedItem.equals("Tìm IP của tên miền")) {
           frmIPTenMien readFile = new frmIPTenMien();
           
           readFile.setVisible(true);
            
        }else if (selectedItem.equals("Tìm tên miền của IP")) {
           frmTimTenMien readFiles = new frmTimTenMien();
           
           readFiles.setVisible(true);
            
        }else if (selectedItem.equals("Tìm IP của máy cục bộ")) {
           frmIPMayCucBo readFiless = new frmIPMayCucBo();
           
           readFiless.setVisible(true);
            
        }else if (selectedItem.equals("Kiểm tra IP.")) {
           frmKTIP2 readFilesss = new frmKTIP2();
           
           readFilesss.setVisible(true);
            
        }else if (selectedItem.equals("Kiểm tra 2 tên miền")) {
           frmKT2Mien readFilessss = new frmKT2Mien();
           
           readFilessss.setVisible(true);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbChucNangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmthltm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmthltm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmthltm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmthltm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmthltm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbChucNang;
    private javax.swing.JComboBox cmbHeThong;
    // End of variables declaration//GEN-END:variables
}
